package responses

const (
	InvalidRequest         = "invalid_request"
	ValidationError        = "validation_error"
	ServerError            = "server_error"
	InvalidCredentials     = "invalid_credentials"
	ClientRequired         = "client_required"
	InvalidClient          = "invalid_client"
	NotImplemented         = "not_implemented"
	Forbidden              = "forbidden"
	UserExists             = "user_exists"
	NotFound               = "not_found"
	ProfileNotFound        = "profile_not_found"
	SessionNotFound        = "session_not_found"
	SessionExpired         = "session_expired"
	TooManyVerifyRequest   = "too_many_verify_request"
	TooManyResetRequest    = "too_many_reset_request"
	InvalidCode            = "invalid_reset_code"
	CodeExpired            = "reset_code_expired"
	AlreadyVerified        = "already_verified"
	AlreadyExists          = "already_exists"
	SocialProviderNotFound = "social_provider_not_found"
	ResetPasswordCodeSent  = "reset_password_code_sent"
	TokenExpired           = "token_expired"
	InvalidToken           = "invalid_token"
	TokenMalformed         = "token_malformed"
	NotSupported           = "not_supported"
)
