version: "3.8"

services:
  usercore_app:
    image: usercore/usercore:0.0.1-dev # Change this to the image hash if you build the image locally
    container_name: usercore_app
    depends_on:
      usercore_database:
        condition: service_healthy
    env_file:
      - ./service/.env.dev
    networks:
      - usercore_net
    #volumes:
    # - app_data:/app
    ports:
      - 8000:8000
      - 9000:9000
    secrets:
      - jwt_private_key
      - jwt_public_key
      - clients
      - db_password
      - server_cert.pem
      - cache_password
    deploy:
      restart_policy:
        condition: on-failure
  usercore_cache:
    image: redis:latest
    container_name: usercore_cache
    hostname: usercore_cache
    networks:
      - usercore_net
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - cache_password
    environment:
      REDIS_PASSWORD: run/secrets/cache_password
      REDIS_USER: usercore
      REDIS_PORT: 6379
    #volumes:
    #  - cache_data:/data
    ports:
      - 6379:6379
  usercore_database:
    image: postgres:latest
    container_name: usercore_database
    hostname: usercore_db
    networks:
      - usercore_net
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "pg_isready -U usercore -d usercore"]
      timeout: 30s
    secrets:
      - db_password
      - source: server_cert.pem
        target: /var/lib/postgresql/server-cert.pem
      - source: server_key.pem
        target: /var/lib/postgresql/server-key.pem
    #volumes:
    #  - db_data:/var/lib/postgresql/data
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server-cert.pem
      -c ssl_key_file=/var/lib/postgresql/server-key.pem
    environment:
      POSTGRES_USER: usercore
      POSTGRES_DB: usercore
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
secrets:
  jwt_private_key:
    file: ./service/vault/example/jwt.private
  jwt_public_key:
    file: ./service/vault/example/jwt.public
  clients:
    file: ./service/vault/example/clients.json
  server_cert.pem:
    file: ./service/vault/example/certs/server-cert.pem
  server_key.pem:
    file: ./service/vault/example/certs/server-key.pem
  cache_password:
    file: ./service/vault/example/redis-pass.txt
  db_password:
    file: ./service/vault/example/db-pass.txt
networks:
  usercore_net:
    driver: bridge
#volumes:
#db_data:
#cache_data:
#app_data:
